spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    check-template-location: true
    suffix:  .html
  profiles:
    active: pro
  messages:
    encoding: utf-8
    basename: i18n/messages
comment.avatar: /images/avatar.jpg

